#!/bin/bash

for m in {1..3}; do
  for n in {5..7}; do
    for k in {3..4}; do
      for l in {7..9}; do
        F=at_least-$m-$n-$k-$l.fm
        echo $F
        ./genip $m $n $k $l >$F
        ./fm -i $F -r x >>$F
      done
    done
  done
done
